Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookWebsite.Data;
using BookWebsite.Models;
using Microsoft.CodeAnalysis.Elfie.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace BookWebsite.Controllers
{
    public class BooksController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<BooksController> _logger;


        //[BindProperty] public IFormFile FileAnh { get; set; }
        public BooksController(ApplicationDbContext context, ILogger<BooksController> logger)
        {
            _context = context;
            _logger = logger;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Book.Include(b => b.TheLoai);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> Index2()
        {
            var applicationDbContext = _context.Book.Include(b => b.TheLoai);
            return View(await applicationDbContext.ToListAsync());
        }
        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Book == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.TheLoai)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            ViewData["TheLoaiId"] = new SelectList(_context.Set<TheLoai>(), "Id", "TenTheLoai");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,TenSach,TacGia,Gia,NXB,NamXB,UrlAnh,MoTa,TheLoaiId")] Book book,IFormFile FileAnh)
        {

            TempData["CreateStatus"] = null;
            if (FileAnh != null && FileAnh.Length > 0)
            {
                // Đường dẫn lưu file
                var filePath = Path.Combine("wwwroot/Image/", FileAnh.FileName);

                // Lưu file vào thư mục trên server
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await FileAnh.CopyToAsync(stream);
                }
                book.UrlAnh = "Image/" + FileAnh.FileName;
            }
          
            if (ModelState.IsValid)
            {
                _context.Add(book);
                await _context.SaveChangesAsync();
                TempData["CreateStatus"] = true;
                return RedirectToAction(nameof(Index));
            }

            if (!ModelState.IsValid)
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage);
                foreach (var error in errors)
                {
                    _logger.LogError(error);
                }
            }
            ViewData["TheLoaiId"] = new SelectList(_context.Set<TheLoai>(), "Id", "TenTheLoai", book.TheLoaiId);
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Book == null)
            {
                return NotFound();
            }

            var book = await _context.Book.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            ViewData["TheLoaiId"] = new SelectList(_context.Set<TheLoai>(), "Id", "TenTheLoai", book.TheLoaiId);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TenSach,TacGia,Gia,NXB,NamXB,UrlAnh,MoTa,TheLoaiId")] Book book,IFormFile FileAnh)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

            TempData["EditStatus"] = null;

            if (FileAnh != null && FileAnh.Length > 0)
            {
                // Đường dẫn lưu file
                var filePath = Path.Combine("wwwroot/Image/", FileAnh.FileName);

                // Lưu file vào thư mục trên server
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await FileAnh.CopyToAsync(stream);
                }

                // Gán đường dẫn tương đối của ảnh vào thuộc tính UrlAnh
                book.UrlAnh = "Image/" + FileAnh.FileName;
             
            }



            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                    TempData["EditStatus"] = true;
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    _logger.LogError("Có lỗi xảy ra khi chỉnh sửa: " + ex.Message);
                }
            }

            if (!ModelState.IsValid)
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage);
                foreach (var error in errors)
                {
                    _logger.LogError(error);
                }
            }

            ViewData["TheLoaiId"] = new SelectList(_context.Set<TheLoai>(), "Id", "TenTheLoai", book.TheLoaiId);
            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Book == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.TheLoai)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Book == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Book'  is null.");
            }
            var book = await _context.Book.FindAsync(id);
            if (book != null)
            {
                _context.Book.Remove(book);
            }

            TempData["DeleteStatus"] = true;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
          return (_context.Book?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/DonHangsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookWebsite.Data;
using BookWebsite.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace BookWebsite.Controllers
{
    [Authorize(Roles = "Admin,Member")]
    public class DonHangsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<DonHangsController> _logger;

        public DonHangsController(ApplicationDbContext context, ILogger<DonHangsController> logger)
        {
            _context = context;
            _logger = logger;
        }

        // GET: DonHangs
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.DonHang.Include(d => d.NguoiDung);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: DonHangs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.DonHang == null)
            {
                return NotFound();
            }

            var donHang = await _context.DonHang
                .Include(d => d.NguoiDung)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (donHang == null)
            {
                return NotFound();
            }

            return View(donHang);
        }

        // GET: DonHangs/Create
        public IActionResult Create()
        {
            ViewData["IdUser"] = new SelectList(_context.Set<IdentityUser>(), "Id", "UserName");
            return View();
        }

        // POST: DonHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdUser,NgayDat,TongTien")] DonHang donHang)
        {
            if (ModelState.IsValid)
            {
                _context.Add(donHang);
                await _context.SaveChangesAsync();
                _logger.LogError("Da them thanh cong");
                return RedirectToAction(nameof(Index));
                
            }

            ViewData["IdUser"] = new SelectList(_context.Set<IdentityUser>(), "Id", "UserName", donHang.IdUser);
            return View(donHang);
        }

        // GET: DonHangs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.DonHang == null)
            {
                return NotFound();
            }

            var donHang = await _context.DonHang.FindAsync(id);
            if (donHang == null)
            {
                return NotFound();
            }
            ViewData["IdUser"] = new SelectList(_context.Set<IdentityUser>(), "Id", "Id", donHang.IdUser);
            return View(donHang);
        }

        // POST: DonHangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdUser,NgayDat,TongTien")] DonHang donHang)
        {
            if (id != donHang.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(donHang);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DonHangExists(donHang.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdUser"] = new SelectList(_context.Set<IdentityUser>(), "Id", "Id", donHang.IdUser);
            return View(donHang);
        }

        // GET: DonHangs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.DonHang == null)
            {
                return NotFound();
            }

            var donHang = await _context.DonHang
                .Include(d => d.NguoiDung)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (donHang == null)
            {
                return NotFound();
            }

            return View(donHang);
        }

        // POST: DonHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.DonHang == null)
            {
                return Problem("Entity set 'ApplicationDbContext.DonHang'  is null.");
            }
            var donHang = await _context.DonHang.FindAsync(id);
            if (donHang != null)
            {
                _context.DonHang.Remove(donHang);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DonHangExists(int id)
        {
          return (_context.DonHang?.Any(e => e.Id == id)).GetValueOrDefault();
        }


   
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookWebsite.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @if (!User.Identity.IsAuthenticated || !User.IsInRole("Admin") )
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Books" asp-action="Index2">Book Store</a>
                }
                else
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Books" asp-action="Index1">Book Store</a>
                }

  
                
           
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">      
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                if (User.IsInRole("Admin"))
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="TheLoais" asp-action="Index">Trang The Loai</a>
                                }
                                else
                                {
                                   
                                }
                            }
                            
                        </li>
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                if (User.IsInRole("Admin"))
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="LoaiPhuongThucThanhToans" asp-action="Index">Loai Thanh Toan</a>
                                }
                                else
                                {

                                }
                            }
                           
                        </li>
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                if (User.IsInRole("Admin"))
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="DonHangs" asp-action="Index">Don Hang</a>
                                }
                                else
                                {
                       
                                }
                            }
                       
                        </li>

                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                if (User.IsInRole("Admin"))
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="GioHangs" asp-action="Index">Gio Hang</a>
                                }
                                else
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="GioHangs" asp-action="GetUserCart">Giỏ Hàng Của Bạn</a>
                                }
                            }
                        </li>

                       
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                if (User.IsInRole("Admin"))
                                {
                                   <a class="nav-link text-dark" asp-area="" asp-controller="GioHangItems" asp-action="Index">Gio Hang Item</a>
                                }
                           
                            }
                           
                        </li>

                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                if (User.IsInRole("Admin"))
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ThanhToans" asp-action="Index">Thanh Toan</a>
                                }
                                else
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ThanhToans" asp-action="GetUserWallet">Thanh Toán</a>
                                }

                            }
                            
                           
                        </li>
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                if (User.IsInRole("Admin"))
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="DanhGias" asp-action="Index">Danh Gia</a>
                                }

                            } 
                        </li>

                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                if (User.IsInRole("Admin"))
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ChiTietDonHangs" asp-action="Index">Chi Tiet Do Hang</a>
                                }

                            }
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />

                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BookWebsite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>