Models/GioHang.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;

namespace BookWebsite.Models
{
    public class GioHang
    {
        [DisplayName("Mã giỏ hàng")]
        public int Id { get; set; }

        [Required]
        [ForeignKey("NguoiDung")]
        [DisplayName("Tên người dùng")]
        public string IDNguoiDung { get; set; }

        [DisplayName("Tổng tiền")]
        [Column(TypeName = "decimal(18,2)")]
        [DisplayFormat(DataFormatString = "{0:N0} VNĐ", ApplyFormatInEditMode = true)] // Hiển thị giá dưới dạng tiền tệ VND
        public decimal TongTien { get; set; }

        // Navigation property
        public IdentityUser? NguoiDung { get; set; }
 
    }

}

Controllers/GioHangItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookWebsite.Data;
using BookWebsite.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using System.Net;

namespace BookWebsite.Controllers
{
    [Authorize(Roles = "Admin,Member")]
    public class GioHangItemsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<GioHangItemsController> _logger;
        private readonly UserManager<IdentityUser> _userManager;

        public GioHangItemsController(ApplicationDbContext context,ILogger<GioHangItemsController> logger , UserManager<IdentityUser> userManager)
        {
            _context = context;
            _logger = logger;
            _userManager = userManager;
        }
        

        // GET: GioHangItems
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.GioHangItem
                .Include(g => g.Book)
                .Include(g => g.GioHang);

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: GioHangItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.GioHangItem == null)
            {
                return NotFound();
            }

            var gioHangItem = await _context.GioHangItem
                .Include(g => g.Book)
                .Include(g => g.GioHang)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (gioHangItem == null)
            {
                return NotFound();
            }

            return View(gioHangItem);
        }

        // GET: GioHangItems/Create
        public IActionResult Create()
        {
            ViewData["BookId"] = new SelectList(_context.Book, "Id", "TenSach");
            ViewData["GioHangId"] = new SelectList(_context.GioHang, "Id", "IDNguoiDung");
            return View();
        }


        // GET: GioHangItems/Create2
        public async Task<IActionResult> Create2(int BookId)
        {
            // Lấy ID của người dùng
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            // Tìm giỏ hàng dựa trên ID người dùng
            ViewData["GioHang"] = _context.GioHang
                                          .FirstOrDefault(g => g.IDNguoiDung == userId);

            // Lấy sách đã chọn
            ViewData["SelectedBook"] = _context.Book
                                                .FirstOrDefault(b => b.Id == BookId);

 
            return View();
        }

        // POST: GioHangItems/Create2
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create2([Bind("Id,GioHangId,BookId,SoLuong,Gia")] GioHangItem gioHangItem)
        {

            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;


            if (ModelState.IsValid)
            {
                var a = await _context.GioHangItem
                                .Where(model => model.GioHangId == gioHangItem.GioHangId)
                                .Where(model => model.BookId == gioHangItem.BookId)
                                .FirstOrDefaultAsync();

                var gioHang = await _context.GioHang
                                 .FirstOrDefaultAsync(model => model.Id == gioHangItem.GioHangId);


                var book = await _context.Book
                                 .FirstOrDefaultAsync(model => model.Id == gioHangItem.BookId);

                // đã có một cuốn sách giống loại muốn mua nằm trong giỏ hàng
                if (a != null)
                {
  
                    gioHang.TongTien += gioHangItem.SoLuong * book.Gia;

                    a.SoLuong += gioHangItem.SoLuong;


                }
                else
                {

                    _context.Add(gioHangItem);

                    //Gán lại giá của sách giống với model
                    gioHangItem.Gia = book.Gia;

                    if (gioHang != null)
                    {
                        // Cập nhật tổng tiền ngay lập tức
                        gioHang.TongTien += gioHangItem.SoLuong * book.Gia;


                    }
                }

                await _context.SaveChangesAsync();



                return RedirectToAction("Index2","Books");
            }



            ViewData["GioHang"] = _context.GioHang
                                         .FirstOrDefault(g => g.IDNguoiDung == userId);



            ViewData["SelectedBook"] = _context.Book
                                                .FirstOrDefault(b => b.Id == gioHangItem.BookId);
            
            return View(gioHangItem);
        }


        // POST: GioHangItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,GioHangId,BookId,SoLuong,Gia")] GioHangItem gioHangItem)
        {


            if (ModelState.IsValid)
            {
                // Thêm GioHangItem vào cơ sở dữ liệu
                _context.Add(gioHangItem);

                // Lấy đối tượng GioHang tương ứng với GioHangId từ GioHangItem
                var gioHang = await _context.GioHang
                                  .FirstOrDefaultAsync(model => model.Id == gioHangItem.GioHangId);

                var book = await _context.Book
                                 .FirstOrDefaultAsync(model => model.Id == gioHangItem.BookId);
        

                gioHangItem.Gia = book.Gia;
         

                if (gioHang != null)
                {
                    // Cập nhật tổng tiền ngay lập tức
                    gioHang.TongTien += gioHangItem.SoLuong * book.Gia;

                    // Lưu thay đổi vào cơ sở dữ liệu
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }
            ViewData["BookId"] = new SelectList(_context.Book, "Id", "TenSach", gioHangItem.BookId);
            ViewData["GioHangId"] = new SelectList(_context.GioHang, "Id", "IDNguoiDung", gioHangItem.GioHangId);
            return View(gioHangItem);
        }

        // GET: GioHangItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.GioHangItem == null)
            {
                return NotFound();
            }

            var gioHangItem = await _context.GioHangItem.FindAsync(id);
            if (gioHangItem == null)
            {
                return NotFound();
            }
            ViewData["BookId"] = new SelectList(_context.Book, "Id", "NXB", gioHangItem.BookId);
            ViewData["GioHangId"] = new SelectList(_context.GioHang, "Id", "IDNguoiDung", gioHangItem.GioHangId);
            return View(gioHangItem);
        }

        // POST: GioHangItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,GioHangId,BookId,SoLuong,Gia")] GioHangItem gioHangItem)
        {
            if (id != gioHangItem.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gioHangItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GioHangItemExists(gioHangItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookId"] = new SelectList(_context.Book, "Id", "TenSach", gioHangItem.BookId);
            ViewData["GioHangId"] = new SelectList(_context.GioHang, "Id", "IDNguoiDung", gioHangItem.GioHangId);
            return View(gioHangItem);
        }


        // GET: GioHangItems/Edit2/5
        public async Task<IActionResult> Edit2(int? id)
        {
            if (id == null || _context.GioHangItem == null)
            {
                return NotFound();
            }

            var gioHangItem = await _context.GioHangItem.FindAsync(id);

            if (gioHangItem == null)
            {
                return NotFound();
            }

            ViewBag.Book = await _context.Book.FindAsync(gioHangItem.BookId);

            ViewBag.GioHangId = gioHangItem.GioHangId;

            return View(gioHangItem);
        }

        // POST: GioHangItems/Edit2/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit2(int id, [Bind("Id,GioHangId,BookId,SoLuong,Gia")] GioHangItem gioHangItem)
        {
            if (id != gioHangItem.Id)
            {
                return NotFound();
            }

            var GioHang = await _context.GioHang.FindAsync(gioHangItem.GioHangId);

            if (ModelState.IsValid)

Views/GioHangs/Create.cshtml
@model BookWebsite.Models.GioHang

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>GioHang</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-3">
                <label asp-for="IDNguoiDung" class="control-label"></label>
                <select asp-for="IDNguoiDung" class ="form-control" asp-items="ViewBag.IDNguoiDung"></select>
            </div>
            <div class="form-group mb-3">
                <label asp-for="TongTien" class="control-label"></label>
                <input asp-for="TongTien" class="form-control" />
                <span asp-validation-for="TongTien" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/GioHangs/Delete.cshtml
@model BookWebsite.Models.GioHang

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GioHang</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TongTien)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TongTien)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NguoiDung)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NguoiDung.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/GioHangs/Details.cshtml
@model BookWebsite.Models.GioHang
@using Microsoft.AspNetCore.Identity;
@{
    ViewData["Title"] = "Details";
}
<div>
    <h4>Giỏ hàng của bạn</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TongTien)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TongTien)
        </dd>
        <dt class = "col-sm-2">
            Khách hàng
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NguoiDung.UserName)
        </dd>

        <dd class="col-sm-10">
            @if (ViewBag.gioHangitem.Count > 0)
            {
                <a class="btn btn-success" asp-action="TaoDonHang">Thanh Toán </a>
            }
        </dd>

        <table class="table">
            <thead>
                <tr>

                    <th>
                        Tên sách
                    </th>
                    <th>
                        Số lượng
                    </th>
                    <th>
                        Giá
                    </th>


                    <th></th>
                </tr>
            </thead>
            <tbody>

                @for (int i = 0; i < ViewBag.gioHangitem.Count; i++)
                {
                    <tr>
                        <td>@ViewBag.gioHangitem[i].Book.TenSach</td>
                        <td>@ViewBag.gioHangitem[i].SoLuong</td>
                        <td>@ViewBag.gioHangitem[i].Book.Gia</td>

                        <td>
                            <a  class ="btn btn-primary" asp-action="Edit2" asp-controller="GioHangItems" asp-route-id="@ViewBag.gioHangitem[i].Id">Chỉnh sửa</a> 
                            <a  class="btn btn-success" asp-action="Details" asp-controller="GioHangItems" asp-route-id="@ViewBag.gioHangitem[i].Id">Xem sản phẩm</a> 
                            <a  class ="btn btn-danger" asp-action="Delete2" asp-controller="GioHangItems" asp-route-id="@ViewBag.gioHangitem[i].Id">Xóa</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </dl>
</div>
<div>
    @if(User.IsInRole("Admin"))
    {
        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
        <a class="btn btn-success"  asp - action="Index"> Back to List</a>
    }
   
</div>

Views/GioHangs/Edit.cshtml
@model BookWebsite.Models.GioHang

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>GioHang</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group mb-3">
                <label asp-for="IDNguoiDung" class="control-label"></label>
                <select asp-for="IDNguoiDung" class="form-control" asp-items="ViewBag.IDNguoiDung"></select>
                <span asp-validation-for="IDNguoiDung" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="TongTien" class="control-label"></label>
                <input asp-for="TongTien" class="form-control" />
                <span asp-validation-for="TongTien" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/GioHangs/Index.cshtml
@model IEnumerable<BookWebsite.Models.GioHang>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
               Người dùng
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TongTien)
            </th>        
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NguoiDung.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TongTien)
            </td>
        
            <td>
                    <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.Id">Xem chi tiết</a>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Xóa giỏ hàng</a>
                    @if(User.IsInRole("Admin"))
                    {
                        <a class="btn btn-success" asp-action="Edit" asp-route-id="@item.Id">Chỉnh sửa</a>
                    }
                  
                </td>
        </tr>
}
    </tbody>
</table>